radiusserver1	"radius.hotspotsystem.com"
radiusserver2	"radius2.hotspotsystem.com"
radiussecret	"hotsys123"
radiusauthport  1812
radiusacctport  1813
uamserver	"https://customer.hotspotsystem.com/customer/hotspotlogin.php"
radiusnasid	"xxx"
papalwaysok
swapoctets
adminupdatefile "/etc/chilli/local.conf"
uamsecret "hotsys123"
definteriminterval 300

