#!/bin/sh /etc/rc.common

START=92
STOP=92

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/cclient -l0
	procd_set_param respawn
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
	}

	procd_close_instance
}
start() {
	[ -f /tmp/no_cclient ] && return
	start_service
}

