#!/bin/sh /etc/rc.common

START=90
STOP=92

USE_PROCD=1

start_service() {
	insmod hotspot
	ebtables -N hotspot_bridge
	procd_open_instance
	procd_set_param command /usr/bin/hotspot
	procd_set_param respawn
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
	}

	procd_close_instance
}

reload_service() {
	/etc/init.d/chilli.init stop&
	sleep 50 && restart&
}

service_triggers(){
	procd_add_raw_trigger "interface.*" 2000 /etc/init.d/hotspot.init restart
	procd_add_reload_trigger wificfg
}
