#!/bin/sh /etc/rc.common

START=99
STOP=1

USE_PROCD=1

EXTRA_COMMANDS="check_role_reload"

sync_role() {
	local role=2 # agent as default
	local map=$(ubus call wifi map_cfg)
	local mode=$(echo "$map" | jsonfilter -e "@.MapMode")
	local role_l=$(uci get inter_upgrade.default.role)
	[ "$mode" == "1" ] && role=$(echo "$map" | jsonfilter -e "@.DeviceRole")
	[ "$role" = "$role_l" ] && return 1
	uci batch <<- EOF
		set inter_upgrade.default.role=$role
		commit inter_upgrade
	EOF
	return 0
}

start_service() {
	sync_role
	procd_open_instance
	procd_set_param command /usr/bin/inter_upgrade
	procd_set_param respawn
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
	}

	procd_close_instance
}

check_role_reload() {
	sync_role && restart
}

reload_service(){
	restart
}

service_triggers(){
	local conf
	local confs=$(grep -E "^[A-Za-z]" /etc/synconf | cut -d'.' -f1 | sort -u)
	procd_add_reload_trigger "inter_upgrade"
	procd_add_config_trigger "config.change" "wificfg" $initscript check_role_reload
	for conf in $confs; do
		procd_add_config_trigger "config.change" "$conf" ubus call inter_upgrade sync_conf '{"delay":5}'
	done
}
