#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=96

. /lib/functions/leds.sh

function led_2G_action() {
	echo "Please define your led_2G_action() function in /lib/functions/led_wifi_*.sh based on wifi chipset." > /dev/console
}

function led_5G_action() {
	echo "Please define your led_5G_action() function in /lib/functions/led_wifi_*.sh based on wifi chipset." > /dev/console
}

for file in $(ls /lib/functions/led_wifi_*.sh); do
	source $file
done

load_led() {
	local name
	local sysfs
	local trigger
	local dev
	local ports
	local mode
	local default
	local delayon
	local delayoff
	local interval

	config_get sysfs $1 sysfs
	config_get name $1 name "$sysfs"
	config_get trigger $1 trigger "none"
	config_get dev $1 dev
	config_get ports $1 port
	config_get mode $1 mode
	config_get_bool default $1 default "0"
	config_get delayon $1 delayon
	config_get delayoff $1 delayoff
	config_get interval $1 interval "50"
	config_get port_state $1 port_state
	config_get delay $1 delay "150"
	config_get message $1 message ""
	config_get gpio $1 gpio "0"
	config_get inverted $1 inverted "0"

	#specially, handle wifi leds here.
	local state
	config_get state $1 state "blink"
	[ -n "$2" ] && state=$2
	if [ "$1" == "led_2G" ]; then
		led_2G_action "$state"
		return
	elif [ "$1" == "led_5G" ]; then
		led_5G_action "$state"
		return
	fi

	if [ "$trigger" = "rssi" ]; then
		# handled by rssileds userspace process
		return
	fi

	[ "$trigger" = "usbdev" ] && {
		# Backward compatibility: translate to the new trigger
		trigger="usbport"
		# Translate port of root hub, e.g. 4-1 -> usb4-port1
		ports=$(echo "$dev" | sed -n 's/^\([0-9]*\)-\([0-9]*\)$/usb\1-port\2/p')
		# Translate port of extra hub, e.g. 2-2.4 -> 2-2-port4
		[ -z "$ports" ] && ports=$(echo "$dev" | sed -n 's/\./-port/p')
	}

	[ -e /sys/class/leds/${sysfs}/brightness ] && {
		echo "setting up led ${name}"

		printf "%s %s %d\n" \
			"$sysfs" \
			"$(sed -ne 's/^.*\[\(.*\)\].*$/\1/p' /sys/class/leds/${sysfs}/trigger)" \
			"$(cat /sys/class/leds/${sysfs}/brightness)" \
				>> /var/run/led.state

		[ "$trigger" == "kernel_random" ] && {
			echo 111 > /sys/class/leds/${sysfs}/brightness
			return 1
		}

		[ "$default" = 0 ] &&
			echo 0 >/sys/class/leds/${sysfs}/brightness

		echo $trigger > /sys/class/leds/${sysfs}/trigger 2> /dev/null
		ret="$?"

		[ $default = 1 ] &&
			cat /sys/class/leds/${sysfs}/max_brightness > /sys/class/leds/${sysfs}/brightness

		[ $ret = 0 ] || {
			echo >&2 "Skipping trigger '$trigger' for led '$name' due to missing kernel module"
			return 1
		}
		case "$trigger" in
		"netdev")
			[ -n "$dev" ] && {
				echo $dev > /sys/class/leds/${sysfs}/device_name
				for m in $mode; do
					[ -e "/sys/class/leds/${sysfs}/$m" ] && \
						echo 1 > /sys/class/leds/${sysfs}/$m
				done
				echo $interval > /sys/class/leds/${sysfs}/interval
			}
			;;

		"timer"|"oneshot")
			[ -n "$delayon" ] && \
				echo $delayon > /sys/class/leds/${sysfs}/delay_on
			[ -n "$delayoff" ] && \
				echo $delayoff > /sys/class/leds/${sysfs}/delay_off
			;;

		"usbport")
			local p

			for p in $ports; do
				echo 1 > /sys/class/leds/${sysfs}/ports/$p
			done
			;;

		"port_state")
			[ -n "$port_state" ] && \
				echo $port_state > /sys/class/leds/${sysfs}/port_state
			;;

		"gpio")
			echo $gpio > /sys/class/leds/${sysfs}/gpio
			echo $inverted > /sys/class/leds/${sysfs}/inverted
			;;

		switch[0-9]*)
			local port_mask speed_mask

			config_get port_mask $1 port_mask
			[ -n "$port_mask" ] && \
				echo $port_mask > /sys/class/leds/${sysfs}/port_mask
			config_get speed_mask $1 speed_mask
			[ -n "$speed_mask" ] && \
				echo $speed_mask > /sys/class/leds/${sysfs}/speed_mask
			[ -n "$mode" ] && \
				echo "$mode" > /sys/class/leds/${sysfs}/mode
			;;
		esac
	}
}

get_ledoff()
{
	local section sectype led
	for section in ${CONFIG_SECTIONS}; do
		config_get sectype $section TYPE
		[ "$sectype" == "system" ] && {
			config_get led $section ledoff 0
			echo $led
			return
		}
	done
	echo 0
}

op_all_led()
{
	local led brightness trigger

	status_led_uncontrollable
	[ $? -gt 0 ] && return

	if [ "$1" == "off" ]; then
		brightness=0
		trigger=none
		for led in $(ls /sys/class/leds/); do
			[ "${led:0:9}" == "led::wifi" ] && continue
			echo $brightness >/sys/class/leds/${led}/brightness 2>/dev/null
			echo $trigger > /sys/class/leds/${led}/trigger 2>/dev/null
		done
		load_led led_2G off
		load_led led_5G off
	elif [ "$1" == "on" ]; then
		brightness=255
		trigger=default-on
		for led in $(ls /sys/class/leds/); do
			[ "${led:0:9}" == "led::wifi" ] && continue
			echo $brightness >/sys/class/leds/${led}/brightness 2>/dev/null
			echo $trigger > /sys/class/leds/${led}/trigger 2>/dev/null
		done
		load_led led_2G on
		load_led led_5G on
	elif [ "$1" == "blink" ]; then
		op_all_led off
		while true
		do
			brightness=255
			trigger=default-on
			for led in $(ls /sys/class/leds/); do
				[ "${led:0:9}" == "led::wifi" ] && continue
				echo $brightness >/sys/class/leds/${led}/brightness 2>/dev/null
				echo $trigger > /sys/class/leds/${led}/trigger 2>/dev/null
		done
			sleep 1
			brightness=0
			trigger=none
			for led in $(ls /sys/class/leds/); do
				[ "${led:0:9}" == "led::wifi" ] && continue
				echo $brightness >/sys/class/leds/${led}/brightness 2>/dev/null
				echo $trigger > /sys/class/leds/${led}/trigger 2>/dev/null
			done
			sleep 1
		done
	else
		brightness=1
		trigger=none
		op_all_led off
		for led in $(ls -d /sys/class/leds/led\:\:port* /sys/class/leds/led\:\:phy* /sys/class/leds/led\:\:wan*); do
			echo $brightness > ${led}/brightness 2>/dev/null
			echo $trigger > ${led}/trigger 2>/dev/null
		done
		load_led led_2G
		load_led led_5G
	fi
}

all()
{
	if [ "$1" == "on" ] || [ "$1" == "off" ] || [ "$1" == "blink" ]; then
		op_all_led $1
	else
		start
	fi
}

extra_command "all" "all [on|off|blink|normal]"

start() {
	status_led_uncontrollable
	[ $? -gt 0 ] && return

	[ -e /sys/class/leds/ ] && {
		[ -s /var/run/led.state ] && {
			local led trigger brightness
			while read led trigger brightness; do
				[ -e "/sys/class/leds/$led/trigger" ] && \
					echo "$trigger" > "/sys/class/leds/$led/trigger"

				[ -e "/sys/class/leds/$led/brightness" ] && \
					echo "$brightness" > "/sys/class/leds/$led/brightness"
			done < /var/run/led.state
			rm /var/run/led.state
		}

		config_load system
		if [ "$(get_ledoff)" == "1" ]; then
			echo turn all leds off.
			op_all_led off
			return
		else
			op_all_led normal
		fi
		UCI_CONFIG_DIR=/tmp/leduci config_load system
		config_foreach load_led led
	}
}
