#!/bin/sh /etc/rc.common

START=97
STOP=99

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/roam
	procd_set_param respawn
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
	}

	procd_close_instance
}

reload_service(){
	sleep 30&&stop&&start&
}

service_triggers(){
	procd_add_reload_trigger wificfg
}

