#!/bin/sh /etc/rc.common

START=21
STOP=90

boot() {
	#for compatibility
	[ -L "/etc/wireless/mediatek" ] || {
		rm -fr /etc/wireless/mediatek
		ln -sf /tmp/mtk/wifi /etc/wireless/mediatek
	}

	mkdir -p /tmp/mtk/wifi
	cp -fr /etc/wireless/mediatek_ro/* /etc/wireless/mediatek/

	applywifi.lua syncCfgOnly
	start
}

start() {
    ubus -t 120 wait_for network
    /sbin/wifi up
}

reload() {
    /sbin/wifi reload_legacy
}

stop() {
    /sbin/wifi down
}

shutdown() {
    /sbin/wifi down
}
