#!/bin/sh /etc/rc.common

START=21
STOP=92

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/net_detect
	procd_set_param respawn
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
	}

	procd_close_instance
}

service_triggers(){
	procd_add_raw_trigger "interface.*" 1000 ubus call net_detect net_detect_sleep '{"time":30}'
}
