#!/bin/sh /etc/rc.common

START=19

apcli_ifname()
{
	local apclis=""

	for card_idx in $(seq 0 1); do
		local card_ext_ifname_all=$(datconf -f /etc/wireless/l1profile.dat get INDEX${card_idx}_ext_ifname 2>/dev/null)
		[ -z "$card_ext_ifname_all" ] && continue
		local card_apcli_ifname_all=$(datconf -f /etc/wireless/l1profile.dat get INDEX${card_idx}_apcli_ifname)

		local idx=0
		while [ true ]; do
			idx=$(($idx+1))
			local card_ext_ifname=$(echo $card_ext_ifname_all | awk -F ';' "{print \$$idx}")
			[ -z "$card_ext_ifname" ] && break
			local card_apcli_ifname=$(echo $card_apcli_ifname_all | awk -F ';' "{print \$$idx}")
			if [ $idx -eq 1 ]; then
				apclis="${apclis}${card_apcli_ifname}0"
			else
				apclis="${apclis},${card_apcli_ifname}0"
			fi
		done
	done

	echo $apclis
}

boot() {
	local devs=""
	local wan=$(uci get network.dev_wan1_raw.name 2> /dev/null)
	local apcli=$(apcli_ifname)

	[ "$wan" != "" ] && devs="$wan"
	[ "$apcli" != "" ] && devs="${devs},${apcli}"

	echo -n "$devs" > /sys/module/netinfo/parameters/mac_host_skip_dev
}

