#!/bin/sh /etc/rc.common

START=99
STOP=92

USE_PROCD=1
MIRROR_CMD=""

function register_port_mirror() {
	local idx=0
	local cnt
	local server_type=""
	local src
	local dst
	local lan_id
	local cmd=""

    while uci get diagnosis.@diag[${idx}] > /dev/null 2>&1
    do
		server_type=$(uci show diagnosis.@diag[${idx}].server_type | awk -F [=\'] '{print $3}')

		if [[ "${server_type}" == "all" ]]; then
			src=$(uci show network.wan1.device | awk -F [=\'] '{print $3}')
		else
			cnt=0
			while uci get network.@interface[${cnt}] > /dev/null 2>&1
			do
				if [[ "${server_type}" == "$(uci show network.@interface[${cnt}].service_type | awk -F [=\'] '{print $3}')" ]]; then
					src=$(uci show network.@interface[${cnt}].device | awk -F [=\'] '{print $3}')
					break
				fi
				cnt=$((cnt+1))
			done
		fi

		lan_id=$(uci show diagnosis.@diag[${idx}].dst | awk -F [n\'] '{print $4}')
		dst=$(ubus call platform_hal portidx_to_ifname "{\"idx\":$lan_id}" | grep "ifname" | awk -F [:\"] '{print $5}')
        if [[ ${idx} == 0 ]]; then
			cmd="${cmd}${src}:${dst}"
        else
            cmd="${cmd};${src}:${dst}"
        fi
        idx=$((idx+1))
    done

	echo ${cmd} > /sys/module/soft_mirror/parameters/mirror
}

diagnosis_start() {
	local src_port=""
	local dst_port=""
	local lan_id
	local cnt

	cfg="$1"
  config_get src "$cfg" src
  if [ -n "$src" ]; then
  	if [ "$src" == "all" ]; then
  		cnt=0
			while uci get network.@interface[${cnt}] > /dev/null 2>&1
			do
				if [[ "internet" == "$(uci show network.@interface[${cnt}].service_type | awk -F [=\'] '{print $3}')" ]]; then
					if [ -z "$src_port" ] ; then
						src_port=$(uci show network.@interface[${cnt}].device | awk -F [=\'] '{print $3}')
					else
						src_port="${src_port},$(uci show network.@interface[${cnt}].device | awk -F [=\'] '{print $3}')"
					fi	
				fi
				cnt=$((cnt+1))
			done
  	else
  		src_port=$(uci show network.$src.device | awk -F [=\'] '{print $3}')
  	fi
  else
  	config_get server_type "$cfg" server_type
  	if [ "$server_type" == "all" ]; then
			src_port=$(uci show network.wan1.device | awk -F [=\'] '{print $3}')
		elif [ -n "$server_type" ] ; then
			cnt=0
			while uci get network.@interface[${cnt}] > /dev/null 2>&1
			do
				if [[ "${server_type}" == "$(uci show network.@interface[${cnt}].service_type | awk -F [=\'] '{print $3}')" ]]; then
					src_port=$(uci show network.@interface[${cnt}].device | awk -F [=\'] '{print $3}')
					break
				fi
				cnt=$((cnt+1))
			done
		else 
			src_port=""
		fi
  fi
  
  config_get dst "$cfg" dst
  lan_id=${dst:3:1}
	dst_port=$(ubus call platform_hal portidx_to_ifname "{\"idx\":$lan_id}" | grep "ifname" | awk -F [:\"] '{print $5}')
	
	[ -z "$src_port" ] || [ -z "$dst_port" ] && return
	
	if [ -z "$MIRROR_CMD" ] ; then
		MIRROR_CMD="${MIRROR_CMD}${src_port}:${dst_port}"
  else
    MIRROR_CMD="${MIRROR_CMD};${src_port}:${dst_port}"
	fi 
}

register_port_mirror_new() {
	config_load diagnosis
	config_foreach diagnosis_start diag
	echo ${MIRROR_CMD} > /sys/module/soft_mirror/parameters/mirror
}

start_service() {
	procd_open_instance
#	procd_set_param command /usr/bin/network_diagnosis
	procd_set_param respawn
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
	}

#	register_port_mirror
	register_port_mirror_new
	procd_close_instance
}


#set wireless only
reload_service() {
#	register_port_mirror
	register_port_mirror_new
}

service_triggers()
{
	procd_add_reload_trigger diagnosis
	procd_add_raw_trigger "interface.*" 1000 /etc/init.d/network_diagnosis reload
	procd_add_config_trigger "config.change" "network" /etc/init.d/network_diagnosis reload
}
