#!/bin/sh /etc/rc.common

START=20
STOP=90

USE_PROCD=1

ifname_to_switch_port() {
	local label
	for port in $(seq 0 5); do
		label=$(cat /proc/device-tree/ethernet@15100000/mdio-bus/switch@0/ports/port@${port}/label)
		[ "$label" == "$1" ] && {
			echo $port
			return 0
		}
	done
}

# only one iptv wan is supported
switch_iptv() {
	local i
	local port
	local wanif
	local mask=0
	local iptvports
	local INTERFACES="$(cat /etc/interfaces)"
	local iptvwan=$(uci show network | grep "service_type='iptv'" | cut -d'.' -f2)
	[ -z "$iptvwan" ] && {
		# no iptv is set
		switch reg w -1 0
		return
	}

	wanif=$(uci get network.dev_${iptvwan}_qvlan.ifname)
	[ ${wanif:0:3} != "lan" ] && {
		# wan is not on mt7531
		switch reg w -1 0
		return
	}
	port=$(ifname_to_switch_port $wanif)
	mask=$((1<<$port))
	mask=$((($mask<<16)|$mask))

	iptvports=$(uci get network.${iptvwan}.bindports)
	for i in $(seq 0 15); do
		[ $((iptvports&(1<<$i))) -eq 0 ] && continue
		ifname=$(echo "${INTERFACES}" | awk "{print \$$(($i+1))}")
		port=$(ifname_to_switch_port $ifname)
		mask=$(($mask|(1<<$port)))
	done
	mask=$(printf "%x" $mask)
	switch reg w -1 $mask
}

init_switch() {
	setup_switch() { return 0; }

	include /lib/network
	setup_switch
	switch_iptv
}

start_service() {
	init_switch

	procd_open_instance
	procd_set_param command /sbin/netifd
	procd_set_param respawn
	procd_set_param watch network.interface
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
	}
	procd_close_instance
}

reload_service() {
	local rv=0

	init_switch
	ubus call network reload || rv=1
	return $rv
}

stop_service() {
	ifdown -a
	sleep 1
}




service_running() {
        ubus -t 120 wait_for network.interface
}

validate_atm_bridge_section()
{
	uci_validate_section network "atm-bridge" "${1}" \
		'unit:uinteger:0' \
		'vci:range(32, 65535):35' \
		'vpi:range(0, 255):8' \
		'atmdev:uinteger:0' \
		'encaps:or("llc", "vc"):llc' \
		'payload:or("bridged", "routed"):bridged'
}

validate_route_section()
{
	uci_validate_section network route "${1}" \
		'interface:string' \
		'target:cidr4' \
		'netmask:netmask4' \
		'gateway:ip4addr' \
		'metric:uinteger' \
		'mtu:uinteger' \
		'table:or(range(0,65535),string)'
}

validate_route6_section()
{
	uci_validate_section network route6 "${1}" \
		'interface:string' \
		'target:cidr6' \
		'gateway:ip6addr' \
		'metric:uinteger' \
		'mtu:uinteger' \
		'table:or(range(0,65535),string)'
}

validate_rule_section()
{
	uci_validate_section network rule "${1}" \
		'in:string' \
		'out:string' \
		'src:cidr4' \
		'dest:cidr4' \
		'tos:range(0,31)' \
		'mark:string' \
		'invert:bool' \
		'lookup:or(range(0,65535),string)' \
		'goto:range(0,65535)' \
		'action:or("prohibit", "unreachable", "blackhole", "throw")'
}

validate_rule6_section()
{
	uci_validate_section network rule6 "${1}" \
		'in:string' \
		'out:string' \
		'src:cidr6' \
		'dest:cidr6' \
		'tos:range(0,31)' \
		'mark:string' \
		'invert:bool' \
		'lookup:or(range(0,65535),string)' \
		'goto:range(0,65535)' \
		'action:or("prohibit", "unreachable", "blackhole", "throw")'
}

validate_switch_section()
{
	uci_validate_section network switch "${1}" \
		'name:string' \
		'enable:bool' \
		'enable_vlan:bool' \
		'reset:bool' \
		'ar8xxx_mib_poll_interval:uinteger' \
		'ar8xxx_mib_type:range(0,1)'
}

validate_switch_vlan()
{
	uci_validate_section network switch_vlan "${1}" \
		'device:string' \
		'vlan:uinteger' \
		'ports:list(ports)'
}

service_triggers()
{
	procd_add_reload_trigger network

	procd_open_validate
	validate_atm_bridge_section
	validate_route_section
	[ -e /proc/sys/net/ipv6 ] && validate_route6_section
	validate_rule_section
	[ -e /proc/sys/net/ipv6 ] && validate_rule6_section
	validate_switch_section
	validate_switch_vlan
	procd_close_validate
}

shutdown() {
        ifdown -a
        sleep 1
}

extra_command "init_switch" "init_switch"
