#!/bin/sh /etc/rc.common

START=99
STOP=92

USE_PROCD=1

[ -d /tmp/trace ] || mkdir /tmp/trace
deal_crash(){
	sfile=/sys/fs/pstore/console-ramoops-0
	[ ! -f  "$sfile" ] && return
	cp -f $sfile /tmp/kernel_last_log
	cat  $sfile |sed -n '/panic_msg/,$p'  > /tmp/crash1
	cat  $sfile |sed -n '/Internal error:/,$p'  > /tmp/crash2
	cat  /tmp/crash1 |sed -n 's/^.*] //p' > /tmp/crash
	[ -s /tmp/crash ] || cat  /tmp/crash2 |sed -n 's/^.*] //p' > /tmp/crash
	rm -f /tmp/crash1
	rm -f /tmp/crash2
	[ ! -s /tmp/crash ] && rm -f /tmp/crash
}

start_service() {
	deal_crash
	rm -rf /sys/fs/pstore/*
	procd_open_instance
	procd_set_param command /usr/bin/panic_trace
	procd_set_param respawn
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
	}

	procd_close_instance
}
reload_service(){
	restart
}
service_triggers(){
	procd_add_reload_trigger "auto_update"
}


