#!/bin/sh /etc/rc.common

START=18
STOP=99

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/platform_hal
	procd_set_param respawn
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
	}

	procd_close_instance

	sleep 3 && ubus call platform_hal wifi_acl_reload '{"delay":35}' &
}

#set wireless only
reload_service() {
	/usr/bin/applywifi.lua
	return 0
}

service_triggers()
{
	procd_add_reload_trigger wificfg
	procd_add_config_trigger "config.change" "network" /usr/bin/mtketherblack reload
	procd_add_config_trigger "config.change" "wifiacl" ubus call platform_hal wifi_acl_reload
}
