#!/bin/sh

. /lib/functions.sh
. /usr/share/libubox/jshn.sh

INTERVAL=5
BASEDIR="/var/run/mwan3track"

write_status(){
	[ "`read_status $1`" = "$2" ] && return
	mkdir -p ${BASEDIR}/$1
	echo $2 > ${BASEDIR}/$1/STATUS
	ubus send wan_status "{\"iface\":\"$1\", \"status\":\"$2\"}"
}

read_status(){
	cat ${BASEDIR}/$1/STATUS 2>/dev/null
}

update_led_wan(){
	local iface status

	for iface in `ls ${BASEDIR}`; do
		status=$(read_status $iface)
		[ $status == "online" ] && break
	done

	[ "$status" == "online" ] && led_event INTERNET_UP || led_event INTERNET_DOWN
	ubus send wan_status "{\"iface\":\"system_wan\", \"status\":\"$status\"}"
}

check_ping(){
	local iface ifname ipaddr dst dsts status metric route option
	local dst_ipv4="www.amazon.com www.microsoft.com"
	local dst_ipv6="2001:4860:4860::8844 2001:4860:4860::8888 2620:0:ccd::2 2620:0:ccc::2"

	iface=$1
	ifname=$2
	ipaddr=$3

	if echo $ipaddr | grep ":"; then
		option="-6"
		dsts=$dst_ipv6
	else
		option="-4"
		dsts=$dst_ipv4
	fi

	status="offline"
	for dst in $dsts; do
		ping -I $ifname -c 1 -W 2 -s 56 -t 60 -q $dst > /dev/null 2>&1 && status="online" && break
	done

	[ "`read_status $iface`" != "$status" ] && write_status $iface $status

	#update default route.
	#default via 192.168.100.1 dev eth0.2  proto static  metric 1
	#config_get metric $iface metric 0
	metric=$(uci get network.$iface.metric)||metric=1
	[ "$status" = "offline" ] && metric=$(($metric+400))
	route_old=$(ip $option ro | grep -E "default.*$ifname")
	route_new=$(echo "$route_old" | sed "s/metric [0-9]*/metric $metric/g")
	if [ "$route_new" != "$route_old" ]; then
		ip $option ro add $route_new && ip $option ro del $route_old
	fi
}

check_dns(){
	local iface ifname ipaddr dst dsts status metric route option
	local dst_ipv4="www.amazon.com www.microsoft.com"
	local dst_ipv6="2001:4860:4860::8844 2001:4860:4860::8888 2620:0:ccd::2 2620:0:ccc::2"
	local idx="1"
	local is_china="0"
	local login=$(uci get customer.info.login)
	if [ "$login" == "leike.cc" ]; then
		dst_ipv4="www.baidu.com www.taobao.com"
		is_china="1"
	fi

	iface=$1
	ifname=$2
	ipaddr=$3

	status="offline"
	if echo $ipaddr | grep ":"; then
		option="-6"
		dsts=$dst_ipv6
		for dst in $dsts; do
			ping -I $ifname -c 1 -W 2 -s 56 -t 60 -q $dst > /dev/null 2>&1 && status="online" && break
		done
	else
		option="-4"
		dsts=$dst_ipv4
		if [ "$iface" == "wan_lte" ]; then
			dns_ip=$(grep -A 2 "wan_lte" /tmp/resolv.conf.d/resolv.conf.auto | grep nameserver | cut -d ' ' -f 2)
			for dns in $dns_ip; do
				[ -n "$dns" ] && detect_dns -n $dns -t 5 -I $ifname -L $is_china | grep 0 > /dev/null 2>&1 && status="online" && break
			done
		else
			json_load "$(ubus -S call network.interface.$iface status)"
			json_select "dns-server"
			while json_get_type type "$idx" ; do
				json_get_var dns "$idx"
				[ -n "$dns" ] && detect_dns -n $dns -t 5 -I $ifname -L $is_china | grep 0 > /dev/null 2>&1 && status="online" && break
				idx=$(($idx+1))
			done
		fi
	fi

	[ "`read_status $iface`" != "$status" ] && write_status $iface $status

	#update default route.
	#default via 192.168.100.1 dev eth0.2  proto static  metric 1
	#config_get metric $iface metric 0
	metric=$(uci get network.$iface.metric)||metric=1
	[ "$status" = "offline" ] && metric=$(($metric+400))
	route_old=$(ip $option ro | grep -E "default.*$ifname")
	route_new=$(echo "$route_old" | sed "s/metric [0-9]*/metric $metric/g")
	if [ "$route_new" != "$route_old" ]; then
		ip $option ro add $route_new && ip $option ro del $route_old
	fi
}

check_interface_status () {
	local iface ipaddr
	local status up l3_device
	local login

	iface=$1
	status=$(ubus -S call network.interface.$iface status)
	[ -n "$status" ] && {
		json_load "$status"
		json_get_vars up l3_device
	}
	login=$(uci get customer.info.login)

	if [ "$up" = "1" ] && [ -n "$l3_device" ]; then
		if [ "$(echo $iface | egrep "ipv6|_6")" ]; then
			ipaddr=$(ip -6 addr ls dev $l3_device | sed -ne 's/ *inet6 \([^ \/]*\).* scope global.*/\1/p')
		else
			ipaddr=$(ip -4 addr ls dev $l3_device | sed -ne 's/ *inet \([^ \/]*\).*/\1/p')
		fi
		if [ -n "$ipaddr" ]; then
			if [ "$login" != "netis.cc" ] && [ "$login" != "login.stonet.cc" ]; then
				check_ping $iface $l3_device $ipaddr
			else
				check_dns $iface $l3_device $ipaddr
			fi
		else
			write_status $iface offline
		fi
	else
		write_status $iface offline
	fi
}

remove_nonexistent_iface (){
	local dir iface found
	for dir in `ls ${BASEDIR}`; do
		found=0
		for iface in $allIface; do
			if [ "$dir" = "$iface" ]; then
				found=1
				break
			fi
		done
		if [ $found -ne 1 ]; then
			echo ===remove $dir===
			rm -fr ${BASEDIR}/$dir
		fi
	done
}

main () {
	local iface
	allIface=$(ubus list network.interface.wan* | cut -d'.' -f3)
	for iface in $allIface; do
		check_interface_status $iface
	done
}

while [ true ]; do
	main
	sleep $INTERVAL
	remove_nonexistent_iface
	update_led_wan
done
