#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions/backup_common.sh

function returnerrcode()
{
	cat <<- EOF
		Status: 200 OK
		Content-type: application/json

		{
			"jsonrpc": "2.0",
			"id ": 1,
			"result": [$1]
		}
	EOF
	exec 0<&-
	exec 1>&-
	exec 2>&-
	exec 0</dev/null
	exec 1>/dev/console
	exec 2>&1
}

function cleanup()
{
	rm -fr $UPGRADE_IMG $UPGRADE_IMG.timestamp
}

#urldecode and handle command injection
function urldecode()
{
	str=$1
	len1=0
	len2=${#str}
	while [ $len1 -ne $len2 ]; do
		str=${str//[\"\'\`|\\<>@?*~!();,.\$\^]/}
		str=${str//%/\\x}
		str=${str//+/ }
		str=`printf "$str"`
		len1=$len2
		len2=${#str}
	done
	echo "$str"
}

#trap cleanup EXIT

#handle query string
QUERY_STRING=`urldecode "$QUERY_STRING"`
while [ true ]; do
	param=${QUERY_STRING%%&*}
	QUERY_STRING=${QUERY_STRING#*&}
	val=${param#*=}
	key=${param%=*}
	eval "${key}='${val}'"
	if [ "$param" = "$QUERY_STRING" ] || [ ${#param} -le 0 ]; then
		break
	fi
done

#check sessin id and permission
if [ ${#sid} -ne 32 ]; then
	returnerrcode 6
	exit
fi
access=`ubus call session access "{\"ubus_rpc_session\":\"$sid\",\"object\":\"system\",\"function\":\"upgrade\"}" | grep "true"`
if [ -z "$access" ]; then
	returnerrcode 6
	exit
fi

if [ "$action" == "backup" ]; then
	BACKUP_FILE=backup-$(uci get system.@system[0].hostname)-$(date -I).tar.gz
	BACKUP_FILE_AES="/tmp/$BACKUP_FILE"_aes
	backup_cfg "$BACKUP_FILE_AES"
	ret=$?
	[ $ret -ne 0 ] && {
		returnerrcode $ret
		exit
	}

	cat <<- EOF
		Status: 200 OK
		Content-Type: application/x-targz
		Content-Disposition: attachment; filename="$BACKUP_FILE"

	EOF
	cat $BACKUP_FILE_AES
elif [ "$action" == "restore" ]; then
	BACKUP_FILE_AES=/tmp/backup.tar.gz_aes
	newline=`echo -e "\r"`
	#drop form-data headers
	while [ true ]; do
		read line
	 	if [ "$line" = "$newline" ]; then
	 		break
	 	fi
	done

	#write stdin to file
	cat > $BACKUP_FILE_AES

	#drop form-data footer
	boundary=${CONTENT_TYPE#*boundary=}
	len=$((${#boundary}+8))
	truncate -s -$len $BACKUP_FILE_AES

	restore_cfg "$BACKUP_FILE_AES"
	ret=$?
	[ $ret -ne 0 ] && {
		rm $BACKUP_FILE_AES
		returnerrcode $ret
		exit
	}

	returnerrcode 0
	sleep 1
	echo "=====================param restore OK, reboot==========================="
	reboot
else
	returnerrcode 2
fi

