#! /bin/sh

ipv4_addr=`ifconfig br-lan | grep "inet addr" | awk '{print $2}' | cut -d':' -f2`
ipv6_addr=`ifconfig br-lan | grep -i 'inet6 addr: fe80' | awk '{print $3}' | cut -d'/' -f1`

cat << EOF
Status: 200 OK
Content-type: application/json

{
        "jsonrpc": "2.0",
        "id ": 1,
        "result": [0,{"ipv4_addr":"$ipv4_addr","ipv6_addr":"$ipv6_addr"}]
}
EOF

