#!/bin/sh

. /usr/share/libubox/jshn.sh

function returnerrcode()
{
	cat <<- EOF
		Status: 200 OK
		Content-type: application/json

		{
			"jsonrpc": "2.0",
			"id ": 1,
			"result": [$1]
		}
	EOF
	exec 0<&-
	exec 1>&-
	exec 2>&-
	exec 0</dev/null
	exec 1>/dev/console
	exec 2>&1
}

#urldecode and handle command injection
function urldecode()
{
	str=$1
	len1=0
	len2=${#str}
	while [ $len1 -ne $len2 ]; do
		str=${str//[\"\'\`|\\<>@?*~!();,.\$\^]/}
		str=${str//%/\\x}
		str=${str//+/ }
		str=`printf "$str"`
		len1=$len2
		len2=${#str}
	done
	echo "$str"
}

#ping 
function ping_end()
{
	killall ping
	rm -rf /tmp/ping.txt
}

function ping_start()
{
	ping_end
	ping $1 -c $2 -s $3 > /tmp/ping.txt&
}

function ping_get()
{
	if [ ! -s /tmp/ping.txt ]; then
		echo "ping: Network unreachable" > /tmp/ping.txt&
	fi

	cat <<- EOF
		Status: 200 OK
		Content-type: application/json

		{
			"jsonrpc": "2.0",
			"id ": 1,
			"result": "$(cat /tmp/ping.txt | base64 | tr -d \\n)"
		}
	EOF
}

#tracert
function tracert_end()
{
	killall traceroute
	rm -rf /tmp/traceroute.txt
}

function tracert_start()
{
	tracert_end
	traceroute $1 -m $2 > /tmp/traceroute.txt&
}

function tracert_get()
{
	if [ ! -s /tmp/traceroute.txt ]; then
		echo "traceroute:  Network unreachable" > /tmp/traceroute.txt&
	fi
	cat <<- EOF
		Status: 200 OK
		Content-type: application/json

		{
			"jsonrpc": "2.0",
			"id ": 1,
			"result": "$(cat /tmp/traceroute.txt | base64 | tr -d \\n)"
		}
	EOF
}

function cleanup()
{
	ping_end
	tracert_end
	rm -rf /tmp/logread.txt
}

#trap cleanup EXIT

#handle query string

#QUERY_STRING=`urldecode "$QUERY_STRING"`
while [ true ]; do
	param=${QUERY_STRING%%&*}
	QUERY_STRING=${QUERY_STRING#*&}
	val=${param#*=}
	key=${param%=*}
	eval "${key}='${val}'"
	if [ "$param" = "$QUERY_STRING" ] || [ ${#param} -le 0 ]; then
		break
	fi
done

#check sessin id and permission
if [ ${#sid} -ne 32 ]; then
	returnerrcode 6
	exit
fi
access=`ubus call session access "{\"ubus_rpc_session\":\"$sid\",\"object\":\"system\",\"function\":\"upgrade\"}" | grep "true"`
if [ -z "$access" ]; then
	returnerrcode 6
	exit
fi

if [ "$action" == "ping" ]; then
	if [ "$command" == "start" ]; then
		ping_start $url $count $size 
		returnerrcode 0
	elif [ "$command" == "get" ]; then
		ping_get
	elif [ "$command" == "end" ]; then
		ping_end
		returnerrcode 0
	else
		returnerrcode 2
	fi
elif [ "$action" == "tracert" ]; then
	if [ "$command" == "start" ]; then
		tracert_start $url $max_hop
		returnerrcode 0
	elif [ "$command" == "get" ]; then
		tracert_get
	elif [ "$command" == "end" ]; then
		tracert_end
		returnerrcode 0
	else
		returnerrcode 2
	fi
elif [ "$action" == "logread" ]; then
	logread | base64 > /tmp/logread.txt

	cat <<- EOF
		Status: 200 OK
		Content-type: application/json

		{
			"jsonrpc": "2.0",
			"id ": 1,
			"result": "$(cat /tmp/logread.txt | tr -d \\n)"
		}
	EOF

	rm -rf /tmp/logread.txt

else
	returnerrcode 2
fi

