#!/bin/sh
. /usr/share/libubox/jshn.sh

echo "$@" > /dev/console

function returnerrcode()
{
	cat << EOF
Status: 200 OK
Content-type: application/json

{
	"jsonrpc": "2.0",
	"id ": 1,
	"result": [$1]
}
EOF
	exec 0>&-
	exec 1>&-
}

#urldecode and handle command injection
function urldecode()
{
	str=$1
	len1=0
	len2=${#str}
	while [ $len1 -ne $len2 ]; do
		str=${str//[\"\'\`|\\<>@?*~!();,.]/}
		str=${str//%/\\x}
		str=${str//+/ }
		str=`printf "$str"`
		len1=$len2
		len2=${#str}
	done
	echo "$str"
}

#get request, return test page and exit
if [ "$REQUEST_METHOD" = "GET" ]; then
cat << EOF
Status: 200 OK
Content-Type: text/html

<form action="./upgrade?sid=00000000000000000000000000000000" method="post" enctype="multipart/form-data">
<p>test page for system upgrade</p>
<input type="file" name="file1"/></br>
<input type="submit" value="sub">
</form>
EOF
exit
fi

#handle query string
QUERY_STRING=`urldecode "$QUERY_STRING"`
while [ true ]; do
	param=${QUERY_STRING%%&*}
	QUERY_STRING=${QUERY_STRING#*&}
	val=${param#*=}
	key=${param%=*}
	eval "${key}='${val}'"
	if [ "$param" = "$QUERY_STRING" ] || [ ${#param} -le 0 ]; then
		break
	fi
done

#check sessin id and permission
if [ ${#sid} -ne 32 ]; then
	returnerrcode 6
	exit
fi
access=`ubus call session access "{\"ubus_rpc_session\":\"$sid\",\"object\":\"system\",\"function\":\"upgrade\"}" | grep "true"`
if [ -z "$access" ]; then
	returnerrcode 6
	exit
fi


UPGRADE_IMG=/tmp/fw.bin
newline=`echo -e "\r"`
#drop form-data headers
while [ true ]; do
	read line
 	if [ "$line" = "$newline" ]; then
 		break
 	fi
done

#write stdin to file
cat > $UPGRADE_IMG

#drop form-data footer
boundary=${CONTENT_TYPE#*boundary=}
len=$((${#boundary}+8))
size=$(wc -c $UPGRADE_IMG | awk '{print $1}')
left=$(($size-$len))
truncate -s $left $UPGRADE_IMG
dst=$UPGRADE_IMG

sysupgrade -q -T $dst > /dev/null 2>&1
if [ $? -eq 0 ]; then
	echo "ok! begin upgrade" > /dev/console
	returnerrcode 0
	(sysupgrade $dst> /dev/null 2>&1 &)
else
	returnerrcode 8
	echo "failed check image" > /dev/console
	rm -f $dst
fi
exit

