#!/bin/sh

. /lib/functions.sh

reset_led_show()
{
	/usr/bin/led_set.sh all off 1

	for i in $(seq 1 4); do
		echo 0 >/sys/class/leds/led::internet_blue/brightness 2>/dev/null
		echo none > /sys/class/leds/led::internet_blue/trigger 2> /dev/null
		echo 1 >/sys/class/leds/led::internet_red/brightness
		echo "default-on" > /sys/class/leds/led::internet_red/trigger

		usleep 500000

		echo 0 >/sys/class/leds/led::internet_red/brightness 2>/dev/null
		echo none > /sys/class/leds/led::internet_red/trigger 2> /dev/null
		echo 1 >/sys/class/leds/led::internet_blue/brightness
		echo "default-on" > /sys/class/leds/led::internet_blue/trigger

		usleep 500000
	done

	/etc/init.d/led all on
}

OVERLAY="$( grep ' /overlay ' /proc/mounts )"

case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0
	rm -f /tmp/gen_pwd_enc
	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ ! -f "/tmp/gen_pwd_enc" ];then
		touch /tmp/gen_pwd_enc
		gen_pwd
		#ubus call acap ac_msg_notify '{"type":"gen_pwd", "action":0}'
	fi
	if [ "$SEEN" -ge 6 -a -n "$OVERLAY" ]; then
		echo "FACTORY RESET" > /dev/console
		reset_led_show
		jffs2reset -y
		sleep 1
		sync
		reboot &
	fi
;;
esac

return 0
