#!/bin/sh

uci -q batch <<EOF
	set system.@system[0].hostname='EAP930'
	set system.@system[0].timezone='MSK-3'
	set system.@system[0].zonename='Europe/Moscow'
	set system.@system[0].ttylogin='0'
	set system.@system[0].log_size='64'
	set system.@system[0].urandom_seed='0'

	set system.ntp='timeserver'
	set system.ntp.enabled='1'
	set system.ntp.enable_server='0'
	del system.ntp.server
	add_list system.ntp.server='0.openwrt.pool.ntp.org'
	add_list system.ntp.server='1.openwrt.pool.ntp.org'
	add_list system.ntp.server='2.openwrt.pool.ntp.org'
	add_list system.ntp.server='3.openwrt.pool.ntp.org'
EOF

uci commit system

exit 0
