#!/bin/sh

. /lib/functions/uci-defaults.sh

mediatek_setup_interfaces()
{
	local board="$1"

	case "$board" in
	netis,eap930)
		# Physical LAN = eth1
		ucidef_set_interface_lan "eth1"
		;;
	esac
}

board_config_update
board=$(board_name)
mediatek_setup_interfaces "$board"
board_config_commit

exit 0
